import { Check } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import ProvenanceBadge from "@/components/ProvenanceBadge";
import RiskGauge from "@/components/RiskGauge";
import { SectionHeading } from "@/components/rainvision/primitives";
import type { RainVisionModel } from "@/hooks/useRainVision";

export default function InundationView({ m }: { m: RainVisionModel }) {
  const { location, sourceMode, risk } = m;
  return <><SectionHeading eyebrow="Surface water pressure" title="Prototype inundation risk" description="A transparent rainfall-driven estimate. It does not provide validated street-level depth prediction." action={<ProvenanceBadge status={sourceMode} />} /><div className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><Card data-testid="inundation-risk-card" className="border-slate-200 shadow-sm"><CardHeader><CardTitle>Inundation risk score</CardTitle><CardDescription>Active point · {location.name}</CardDescription></CardHeader><CardContent><div className="flex items-center justify-center py-5"><RiskGauge risk={{ ...risk, score: risk.inundation.score, category: risk.inundation.category }} /></div><div className="flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-sm text-slate-600">Trend</span><strong className="font-mono text-sm text-amber-700">{risk.inundation.trend}</strong></div></CardContent></Card><Card data-testid="inundation-factors-card" className="border-slate-200 shadow-sm"><CardHeader><CardTitle>Contributing factors</CardTitle><CardDescription>Prototype weighting, not a hydrodynamic model</CardDescription></CardHeader><CardContent className="space-y-4">{[["Rainfall intensity", risk.inundation.factors.intensity], ["6h / 24h accumulation", risk.inundation.factors.accumulation], ["Precipitation probability", risk.inundation.factors.probability], ["Urban vulnerability proxy", risk.inundation.factors.vulnerability]].map(([label, value]) => <div key={label as string}><div className="mb-1 flex justify-between text-sm"><span className="text-slate-600">{label}</span><span className="font-mono font-semibold text-slate-900">{Math.round(value as number)}/100</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-500" style={{ width: `${value}%` }} /></div></div>)}<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-relaxed text-amber-950">This prototype does not provide validated street-level flood-depth prediction. Production requires DEM, drainage, river levels, soil moisture, land use, and hydrological or hydrodynamic models.</div></CardContent></Card></div><Card data-testid="inundation-roadmap-card" className="mt-5 border-slate-200 shadow-sm"><CardHeader><CardTitle>Production calibration roadmap</CardTitle><CardDescription>What turns this prototype into an operational decision-support layer</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Historical rainfall events", "Elevation & drainage", "River and soil observations", "Validated hydrological models"].map((item) => <div key={item} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-sm text-slate-700"><Check size={15} className="text-sky-700" />{item}</div>)}</CardContent></Card></>;
}
