import { ChevronRight, RotateCcw, WifiOff, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import ProvenanceBadge from "@/components/ProvenanceBadge";
import { demoStages } from "@/pages/rainvision/config";

export default function EmergencyPanel({ demoStage, start, next, reset, simulateOffline }: { demoStage: number | null; start: () => void; next: () => void; reset: () => void; simulateOffline: () => void }) {
  const active = demoStage !== null;
  return <Card data-testid="emergency-demo-panel" className={`border-slate-200 shadow-sm ${active ? "border-indigo-300 bg-indigo-50/40" : ""}`}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-lg"><Zap size={18} className="text-indigo-700" />Emergency demo mode</CardTitle><CardDescription>Accelerated jury sequence · live data stays clearly separated</CardDescription></div>{active ? <ProvenanceBadge status="DEMO" label="Scenario active" /> : <ProvenanceBadge status="FUTURE" label="Ready" />}</div></CardHeader><CardContent><div className="mb-4 flex flex-wrap gap-1.5">{demoStages.map((stage, index) => <span key={stage} data-testid={`demo-stage-${index}`} className={`rounded-full border px-2 py-1 font-mono text-[9px] font-bold uppercase tracking-wider ${active && index <= demoStage ? "border-indigo-300 bg-indigo-100 text-indigo-900" : "border-slate-200 bg-white text-slate-400"}`}>{index + 1}. {stage}</span>)}</div><div className="flex flex-wrap gap-2"><Button data-testid="button-demo-start" size="sm" onClick={start} disabled={active}><Zap size={14} />Start scenario</Button><Button data-testid="button-demo-next" size="sm" variant="outline" onClick={next} disabled={!active}><ChevronRight size={14} />Next stage</Button><Button data-testid="button-demo-offline" size="sm" variant="outline" onClick={simulateOffline}><WifiOff size={14} />Simulate failure</Button><Button data-testid="button-demo-reset" size="sm" variant="ghost" onClick={reset}><RotateCcw size={14} />Reset demo</Button></div></CardContent></Card>;
}
